global:
  checkNewVersion: false

experimental:
  devPlugin:
    goPath: /plugins
    moduleName: imageopti

entryPoints:
  web:
    address: ":80"
    # http:
      # redirections:
      #   entrypoint:
      #     to: websecure
      #     scheme: https
  websecure:
    address: ":443"

# providers:
  # docker:
    # endpoint: "unix:///var/run/docker.sock"
    # exposedByDefault: false
    # network: traefik-net

metrics:
  prometheus: {}

log:
  level: DEBUG

api:
  insecure: true

# certificatesResolvers:
#   myhttpchallenge:
#     acme:
#       email: antoine.gravelot@hotmail.fr
#       storage: /letsencrypt/acme.json
#       httpChallenge:
#         # used during the challenge
#         entryPoint: web

# tls:
#   options:
#     default:
#       sniStrict: true
#       minVersion: VersionTLS12
#       cipherSuites: 
#         # https://ssl-config.mozilla.org/#server=traefik&version=2.1.2&config=intermediate&guideline=5.4
#         - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
#         - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
#         - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
#         - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
#         - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
#         - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
#     mintls13:
#       minVersion: VersionTLS13