displayName: Image optimizer
type: middleware

import: github.com/agravelot/image_optimizer

summary: 'Image optimizer middleware is a middleware designed to optimize image responses on the fly.'

testData:

